### ISSUE TITLE
Collaboration with Tech for Palestine

### ISSUE THREAD

**Issue by helayoty** [Zain-ul-din/The-Palestinian-Side#6]
Hey,
I'm reaching out as part of the [Tech for Palestine](https://techforpalestine.org) initiative to ask if you would like to join our community as a liaison for this great project. We would love to help you evolve this project, and many volunteers would like to support you.

Looking forward to working with you!

**Comment by Zain-ul-din** [comment]
@helayoty Thank you for reaching out. I already joined your discord server and I'm ready to contribute to the Pro-Palestine Projects. how can I help you?
